socset/socset/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('site/', include('siteland.urls')),
    # path('chat/', include('chat.urls'))
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socset/accounts/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.conf import settings
from django.contrib.auth import get_user_model
from markdown_deux import markdown

from django.contrib.contenttypes.models import ContentType

from django.contrib.auth.models import User

User = get_user_model()

class Photo(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL,
	 							on_delete=models.CASCADE)
	imageuser = models.FileField(upload_to='imageinst', 
						verbose_name='photouser')
	dataimg = models.DateTimeField(auto_now=True, 
									auto_now_add=False)
	photolike = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='post_likes')

	orphotoorvideo = models.BooleanField(default=False)

	def __unicode__(self):
		return self.imageuser


class Chat(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL,
	 on_delete=models.CASCADE)
	useryou = models.ForeignKey(settings.AUTH_USER_MODEL,
	 on_delete=models.CASCADE,
	 related_name="useryou")
	message = models.TextField()
	datamessage = models.DateTimeField(auto_now=True, 
									auto_now_add=False)


	def __str__(self):
		return str(self.user)

	def get_like_url_photo(self):
		return reverse("listusers:likephoto", kwargs={"id": self.id})


class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	avatar = models.ImageField(upload_to='imageusers', verbose_name='Изображение')
	placework = models.TextField(default='Отсутствует')
	city = models.TextField(default='Отсутствует')
	friends = models.ManyToManyField(User, 
				related_name='is_friends',
				blank=True)

	followers = models.ManyToManyField(User, 
				related_name='is_following',
				blank=True)
	zayavkadruzya = models.ManyToManyField(User, 
			related_name='addingfriend',
			blank=True,)

	messagedo = models.ManyToManyField(User, 
				related_name='messagedo',
				blank=True)
	allmessagesstory = models.ManyToManyField(User, 
				related_name='allmessagesstory',
				blank=True)

	last_activity = models.DateTimeField(auto_now=True, 
				auto_now_add=False)




	def __unicode__(self):
		return self.user

	def user_get_absolute_url(self):
		return reverse("accounts:userdetail", kwargs={"id": self.id})


	def get_like_url(self):
		return reverse("foto:like-toggle", kwargs={"id": self.id})

	def get_api_like_url(self):
		return reverse("foto:like-api-toggle", kwargs={"id": self.id})



class Meta:
	verbose_name = 'Профиль'

socset/templates/photo/photos.html
{% load static %}
{% load crispy_forms_tags %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="img/icon.png" type="image/png">
    <link rel="shortcut icon" href="{% static 'img/icon.png' %}" type="image/png">
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  
    <title>FaceVkInsta</title>
  </head>
  <body>
    
    

{% include 'navbar.html' %}

<br><br><br><br>
    <div class="container">  
      <div class="row"> 
          
          
        <div class="col-lg-9 col-md-9 col-xs-12 leftprofile">
          <div class="leftprofilecolor">
          
  <div class="addphoto">
    <form method="post" action="" enctype='multipart/form-data'>
          {% csrf_token %}
          <label for="id_imageuser"></label>
          <input type="file" name="imageuser" required id="id_imageuser" /> 
<label class="videocheck" for="id_orphotoorvideo">Видео.</label>
<input type="checkbox" name="orphotoorvideo" 
 id="id_orphotoorvideo" /> 

 <button type="submit" class="btn btn-primary addphotobutton">Добавить</button>
      </form>
  </div>
  <br><br><hr><br>
          <!-- TEST -->
          <div class="row">
          {% for image in photos %}
          {% if image.user == request.user %}
          <div class="col-lg-6 col-md-6 col-xs-12 col-sm-12">
            
         
          <div class="allfiles">
          {% if image.orphotoorvideo %}
          <video class="img-fluid videoclassall" src="{{ image.imageuser.url }}" controls="controls"></video>
          {%  else %}
          <a href="{{ image.imageuser.url }}">
          <img class="imgclassall" 
          class="img-thumbnail img-fluid"  
          src="{{ image.imageuser.url }}" alt="">
         {% endif %}
          </a>
          <p>{{ image.dataimg }}</p>
          <p><i class="far fa-thumbs-up"></i>

          {{ image.photolike.count }}</p>
          </div>

          <br><hr><br>

             </div> <!-- ../ col-md -->
          {% endif %}
          {% endfor %}
          </div> <!-- ../ row -->
        



        </div>
      </div>

        <div class="col-lg-3 col-md-3 col-xs-12">
          <p class="">BANNER</p>
          <br>
 
        </div>
          
        

      </div>
    </div>

   

    <div style="margin-top: 1000px;"></div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

socset/templates/photo/photoyou.html
{% load static %}
{% load crispy_forms_tags %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="img/icon.png" type="image/png">
    <link rel="shortcut icon" href="{% static 'img/icon.png' %}" type="image/png">
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <title>FaceVkInsta</title>
  </head>
  <body>
    
    

{% include 'navbar.html' %}



<script>
     $(document).ready(function(){
          function updateText(btn, newCount, verb){
          btn.attr("data-likes", newCount)
          btn.text(newCount + " " + verb)
      }
      $(".like-btn").click(function(e){
        e.preventDefault()
        var this_ = $(this)
        var likeUrl = this_.attr("data-href")
        var likeCount = parseInt(this_.attr("data-likes")) | 0
        var addLike = likeCount + 1
        var removeLike = likeCount - 1
        if (likeUrl){
           $.ajax({
            url: likeUrl,
            method: "GET",
            data: {},
            success: function(data){
              console.log(data)
              var newLikes;
              if (data.liked){
                  updateText(this_, addLike, 'Unlike')
              } else {
                  updateText(this_, removeLike, 
                    '<i class="far fa-thumbs-up"></i>')
                  // remove one like
              }
            }, error: function(error){
              console.log(error)
              console.log("error")
            }
          })
        }
       
      })
  })
    </script>


<br><br><br><br>
    <div class="container">  
      <div class="row"> 
          
          
        <div class="col-lg-9 col-md-9 col-xs-12 leftprofile">
          <div class="leftprofilecolor">
          <!-- TEST -->
          <div class="row">
          {% for image in allphoto %}
          {% if image.user == userph.user %}
          <div class="col-lg-6 col-md-6 col-xs-12 col-sm-12">
            
         
          <div class="allfiles">
          {% if image.orphotoorvideo %}
          <video class="img-fluid videoclassall" src="{{ image.imageuser.url }}" controls="controls"></video>
          {%  else %}
          <a href="{{ image.imageuser.url }}">
          <img class="imgclassall" 
          class="img-thumbnail img-fluid"  
          src="{{ image.imageuser.url }}" alt="">
         {% endif %}
          </a>
          <p>{{ image.dataimg }}</p>

          <!-- <p class="likes">
          <a class='like-btn' data-href='{{ instance.get_api_like_url }}' data-likes='{{ instance.likes.count }}' href='{{ instance.get_like_url }}'><i class="far fa-thumbs-up"></i> 
          {{ image.photolike.count }}</a>
            </p> -->
            <p class="like">
            {% if request.user in image.photolike.all %}
              <a href="/photo/{{ image.id }}">
                <i class="far fa-thumbs-up like"></i>
                {{ image.photolike.count }}
              </a>
              {% else %}
              <a href="/photo/{{ image.id }}">
                <i class="far fa-thumbs-up unlike"></i>
                {{ image.photolike.count }}
              </a>
              {% endif %}
            </p>
            <!-- <p class="likeclass">
              <form action="" method="POST">
                {% csrf_token %}
                <input type="hidden" name="runlike">
                {% if request.user in image.photolike.all %}

                <button class="addLikeClass">
                  <i class="far fa-thumbs-up"></i>
                </button>
                {% else %}
                <button class="removeLikeClass">
                  <i class="far fa-thumbs-up"></i>
                </button>
                {% endif %}
                {{ image.photolike.count }}
              </form>
            </p>
            <p>{{ image.user.get_full_name }}</p> -->

          </div>

          <br><hr><br>

             </div> <!-- ../ col-md -->
          {% endif %}
          {% endfor %}
          </div> <!-- ../ row -->
        
        
        



        </div>
      </div>

        <div class="col-lg-3 col-md-3 col-xs-12">
          <p class="">BANNER</p>
          <br>
 
        </div>
          
        

      </div>
    </div>

   

    <div style="margin-top: 1000px;"></div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>