socset/accounts/urls.py
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from .views import *

app_name = 'accounts'

urlpatterns = [
	path('', login_view, name='login_view'),
	path('register/', register_view, name='register'),
	path('logout/', logout_view, name='logout'),
	path('profile/', profilemy, name='profilemy'),
	path('update/', kabinetedit, name='kabinetedit'),
	path('listusers/', listusers, name='listusers'),
	path('listusers/<int:id>/', userdetail, name='userdetail'),
	path('listusers/<int:id>/chat/', chat, name='chat'),
	path('foto/', photomy, name='photomy'),
	path('allchat/', allchat, name='allchat'),
	path('listusers/<int:id>/foto/', photoyou, name='photoyou'),
	path('photo/<int:id>/', likephoto, name='likephoto'),
	path('api/listusers/<int:id>/foto/like/', PostLikeApiToggle.as_view(), name='like-api-toggle'),

]

socset/socset/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('site/', include('siteland.urls')),
    # path('chat/', include('chat.urls'))
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socset/accounts/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.conf import settings
from django.contrib.auth import get_user_model
from markdown_deux import markdown

from django.contrib.contenttypes.models import ContentType

from django.contrib.auth.models import User

User = get_user_model()

class Photo(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL,
	 							on_delete=models.CASCADE)
	imageuser = models.FileField(upload_to='imageinst', 
						verbose_name='photouser')
	dataimg = models.DateTimeField(auto_now=True, 
									auto_now_add=False)
	photolike = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='post_likes')

	orphotoorvideo = models.BooleanField(default=False)

	def __unicode__(self):
		return self.imageuser


class Chat(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL,
	 on_delete=models.CASCADE)
	useryou = models.ForeignKey(settings.AUTH_USER_MODEL,
	 on_delete=models.CASCADE,
	 related_name="useryou")
	message = models.TextField()
	datamessage = models.DateTimeField(auto_now=True, 
									auto_now_add=False)


	def __str__(self):
		return str(self.user)

	def get_like_url_photo(self):
		return reverse("listusers:likephoto", kwargs={"id": self.id})


class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	avatar = models.ImageField(upload_to='imageusers', verbose_name='Изображение')
	placework = models.TextField(default='Отсутствует')
	city = models.TextField(default='Отсутствует')
	friends = models.ManyToManyField(User, 
				related_name='is_friends',
				blank=True)

	followers = models.ManyToManyField(User, 
				related_name='is_following',
				blank=True)
	zayavkadruzya = models.ManyToManyField(User, 
			related_name='addingfriend',
			blank=True,)

	messagedo = models.ManyToManyField(User, 
				related_name='messagedo',
				blank=True)
	allmessagesstory = models.ManyToManyField(User, 
				related_name='allmessagesstory',
				blank=True)

	last_activity = models.DateTimeField(auto_now=True, 
				auto_now_add=False)




	def __unicode__(self):
		return self.user

	def user_get_absolute_url(self):
		return reverse("accounts:userdetail", kwargs={"id": self.id})


	def get_like_url(self):
		return reverse("foto:like-toggle", kwargs={"id": self.id})

	def get_api_like_url(self):
		return reverse("foto:like-api-toggle", kwargs={"id": self.id})



class Meta:
	verbose_name = 'Профиль'

socset/accounts/forms.py
from django import forms

from django.contrib import messages

import json
import urllib

from pagedown.widgets import AdminPagedownWidget

from django.contrib.auth import (
		authenticate,
		get_user_model,
		login,
		logout,
	)

from .models import *

User = get_user_model()

class ChatForm(forms.ModelForm):
    class Meta:
        model = Chat
        exclude = [""]

class UserLoginForm(forms.Form):
	username = forms.CharField(label='')
	password = forms.CharField(label='', widget=forms.PasswordInput)

	def clean(self, *args, **kwargs):
		username = self.cleaned_data.get("username")
		password = self.cleaned_data.get("password")

		if username and password:
			user = authenticate(username=username, password=password)
			if not user:
				raise forms.ValidationError("Пользователь не сушетсвует!")
			if not user.check_password(password):
				raise forms.ValidationError("Не правильный пароль")
			if not user.is_active:
				raise forms.ValidationError("Пользователь забанен")
		return super(UserLoginForm, self).clean(*args, **kwargs)


class UserRegisterForm(forms.ModelForm):
	username = forms.CharField(label='')
	email = forms.CharField(label='')
	password = forms.CharField(label='')
	first_name = forms.CharField(label='')
	last_name = forms.CharField(label='')

	class Meta:
		model = User
		fields = [
			'first_name',
			'last_name',
			'email',
			'username',
			'password',
		]


	def clean_email(self):
		email = self.cleaned_data.get('email')

		email_qs = User.objects.filter(email=email)
		if email_qs.exists():
			raise forms.ValidationError("Емайл уже сушествует")
		return email


class Createimg(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = [
			"avatar",
		]

class Editprofile(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = [
			"avatar",
			"placework",
			"city"
		]

class MessageForm(forms.ModelForm):
	# content = forms.CharField(widget=AdminPagedownWidget)
	class Meta:
		model = Chat
		fields = [
			"message",
			"useryou"
		]

class AddPhoto(forms.ModelForm):
	# content = forms.CharField(widget=AdminPagedownWidget)
	class Meta:
		model = Photo
		fields = [
			"imageuser",
			"orphotoorvideo"
		]

socset/accounts/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect

from django.contrib.auth import (
        authenticate,
        get_user_model,
        login,
        logout,
    )
from django.db.models import Q

from .forms import *
from .models import *

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.models import User
import json
import urllib

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions
from django.contrib.auth.models import User
from django.views.generic import RedirectView


def login_view(request):
    if not request.user.is_authenticated:
        next = request.GET.get('next')
        title = "Login"
        form = UserLoginForm(request.POST or None)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            login(request, user)

            if next:
                return redirect(next)
            return redirect("site/")
        return render(request, "accounts/login.html", {"form": form, "title": title})
    else:
        return render(request, "site/site.html")

def register_view(request):
    next = request.GET.get('next')
    title = "Register"
    form = UserRegisterForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        password = form.cleaned_data.get('password')
        user.set_password(password)
        user.save()

        new_user = authenticate(username=user.username, password=password)
        login(request, new_user)
        if next:
            return redirect(next)
        return redirect("/site/")

    context = {
        "form": form,
        "title": title,
        "buttitle": "Регистрация"
    }
    return render(request, "accounts/register.html", context)

def logout_view(request):
    saveuser = get_object_or_404(UserProfile, user=request.user)
    saveuser.save()
    logout(request)
    return redirect("/")


def profilemy(request):
    formimg = Createimg(request.POST or None, request.FILES or None)
    user = request.user

    zayavka_list = UserProfile.objects.filter(~Q(user=user))

    runaddfriendend = request.POST.get("endaddfriend")
    if runaddfriendend:
        user.userprofile.friends.add(zayavka_list)
        user.userprofile.zayavkadruzya.remove(zayavka_list)


    d = UserProfile.objects.all()
    if formimg.is_valid():
        ins = formimg.save(commit=False)
        ins.user = request.user
        ins.save()
        return redirect("/profile/")
    context = {
        "forming": formimg,
        "zayavka_list": zayavka_list,
    }

    return render(request, 'accounts/profilemy.html', context)

# editprofile
def kabinetedit(request):
    instance = get_object_or_404(UserProfile, user=request.user)
    try:
        profile = request.user.userprofile
    except UserProfile.DoesNotExist:
        profile = UserProfile(user=request.user)

    formimg = Editprofile(request.POST or None,request.FILES or None, instance=instance)
    if request.method == 'POST':
        if formimg.is_valid():
            instance = formimg.save(commit=False)
            instance.save()
            return redirect("/profile/")
    return render(request, 'accounts/kabedit.html', {'formimg': formimg})

def listusers(request):
    users_list = UserProfile.objects.filter(~Q(user=request.user))

    druzya = request.GET.get("q")
    if druzya:
        users_list = users_list.filter(
            Q(user__first_name__icontains=druzya)|
            Q(user__last_name__icontains=druzya)|
            Q(placework__icontains=druzya)|
            Q(city__icontains=druzya)
            ).distinct()

    context = {
            "title": "ListUser",
            "users_list": users_list,
        }
    return render(request, 'accounts/listusers.html', context)


def allchat(request):
    user = request.user
    chatstory = UserProfile.objects.filter(~Q(user=user))
    context = {
        "chatstory":chatstory,
        "user":user,
    }
    return render(request, 'chat/allchat.html', context)



def chat(request, id=None):
    userobjchat = get_object_or_404(UserProfile, id=id)
    allmessages = Chat.objects.all()
    if userobjchat.user in request.user.userprofile.messagedo.all():
        request.user.userprofile.messagedo.remove(userobjchat.user)
    user = request.user
    n = userobjchat.user
    form = MessageForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        if user not in userobjchat.messagedo.all():
            userobjchat.messagedo.add(user)

        if user not in userobjchat.allmessagesstory.all() and n not in user.userprofile.allmessagesstory.all():
            user.userprofile.allmessagesstory.add(n)
            userobjchat.allmessagesstory.add(user)
    else:
        pass
    
    context = {
        "userobjchat": userobjchat,
        "allmessages": allmessages,
        "form": form,
    }
    return render(request, 'chat/chat.html', context)



def userdetail(request, id=None):
    userobj = get_object_or_404(UserProfile, id=id)
    # guser = get_object_or_404(User, id=id)

    user = request.user

    d = UserProfile.objects.all()

    n = userobj.user

    removefriend = request.POST.get("removefriendend")
    if removefriend:
        user.userprofile.friends.remove(n)
        userobj.friends.remove(user)

    addfriendended = request.POST.get("addfriendend")
    if addfriendended:
        user.userprofile.friends.add(n)
        userobj.friends.add(user)
        user.userprofile.zayavkadruzya.remove(n)

    rundobfriend = request.POST.get("dobavfriend")
    if rundobfriend:
        if user in userobj.zayavkadruzya.all():
            userobj.zayavkadruzya.remove(user)
        else:
            userobj.zayavkadruzya.add(user)

    initial_data = {
        "object_id": userobj.id,
    }

    context = {
        "userobj": userobj,
        "user": user,
        "d": d,
    }
    return render(request, 'accounts/profileyou.html', context)


def photomy(request, id=None):
    user = request.user
    allphoto = Photo.objects.all()
    formaphoto = AddPhoto(request.POST or None, request.FILES or None)
    if formaphoto.is_valid():
        instance = formaphoto.save(commit=False)
        instance.user = request.user
        instance.save() 
    context = {
        "photos": allphoto,
        "formaphoto":formaphoto,
    }
    return render(request, 'photo/photos.html', context)

def photoyou(request, id=None):
    userph = get_object_or_404(UserProfile, id=id)
    user = userph.user
    useri = request.user
    allphoto = Photo.objects.all()
    runlikeimage = request.POST.get("runlike")
    context = {
        "userph": userph,
        "allphoto": allphoto,
    }
    return render(request, 'photo/photoyou.html', context)

def likephoto(request, id=None):
    instance = get_object_or_404(Photo, id=id)
    obj = get_object_or_404(UserProfile, id=id)
    user = request.user

    if user in  instance.photolike.all():
        instance.photolike.remove(user)
    else:
        instance.photolike.add(user)

    url_ = obj.user_get_absolute_url()
    

    context = {
        "instance": instance,
    }
    # return url_
    return HttpResponse(url_)


class PostLikeToggle(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        id = self.kwargs.get("id")
        obj = get_object_or_404(Photo, id=id)
        url_ = obj.user_get_absolute_url()
        user = self.request.user
        if user.is_authenticated:
            if user in obj.photolike.all():
                obj.photolike.remove(user)
            else:
                obj.photolike.add(user)
        return url_

class PostLikeApiToggle(APIView):
    
    authentication_classes = (authentication.SessionAuthentication,)
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request, id=None, format=None):
        # id = self.kwargs.get("id")
        obj = user_get_absolute_url(Photo, id=id)
        url_ = obj.user_get_absolute_url()
        user = self.request.user
        updated = False
        liked = False
        if user.is_authenticated:
            if user in obj.photolike.all():
                liked = False
                obj.photolike.remove(user)
            else:
                liked = True
                obj.photolike.add(user)
            updated =  True

        data = {
            "updated":updated,
            "liked": liked
        }

        return Response(data)

socset/templates/accounts/kabedit.html
{% load static %}

{% load crispy_forms_tags %}
{% block head_extra %} 

  {{ form.media }}

{% endblock head_extra %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="img/icon.png" type="image/png">
    <link rel="shortcut icon" href="{% static 'img/icon.png' %}" type="image/png">
    
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  
    <title>FaceVkInsta</title>
  </head>
  <body>
    
    

{% include 'navbar.html' %}

<br><br><br><br>
    <div class="container">  
      <div class="row"> 
          
          
        <div class="col-lg-9 col-md-9 col-xs-12 leftprofile">
          <div class="leftprofilecolor">
          <div class="row">

          <div class="imgandop col-lg-4">

          {% if user.userprofile.avatar %}

          <img class="img-fluid img-thumbnail img-profile" 
          src="{{ user.userprofile.avatar.url }}" alt="">
          {% else %}
          <img class="img-fluid" 
          src="{% static 'img/default_avatar.png' %}">
          {% endif %}
          <br>
          <form class="formtextuseredit" 
          method="POST" action="." enctype='multipart/form-data'>
          {% csrf_token %}


          

<div id="div_id_avatar" class="form-group"> <label for="id_avatar" class="col-form-label  requiredField">
          <span class="asteriskField"></span> </label> <div class="">
                    

<input type="file" name="avatar" id="id_avatar" class="clearablefileinput" /> </div> </div> 


<div id="div_id_placework" class="form-group"> 
<label for="id_placework" class="col-form-label  requiredField">
                Место работы<span class="asteriskField"></span> </label> <div class=""> 
                <textarea name="placework" id="id_placework"    
                class="textarea form-control placeworkedit" 
                required >
{{ user.userprofile.placework }}
</textarea> </div> </div> 


<div id="div_id_city" class="form-group"> 
<label for="id_city" class="col-form-label  requiredField">
                Город<span class="asteriskField"></span> </label> <div class=""> 
                <textarea name="city" id="id_city" 
                class="textarea form-control cityedit" 
                required>
{{ user.userprofile.city }}
</textarea> </div> </div>





      <input type="submit" value="Сохранить"
      class="btn btn-primary saveedit">
      </form>
      

          
          </div>
          <div class="nameprofile col-lg-8">
            <p class="namepr">{{ user.get_full_name }}</p>
            <p>Город - 
            {{ user.userprofile.city }}
            </p>
            <p>Место работы - 
            {{ user.userprofile.placework }}
            </p>
          </div>
          
        </div>
        
        <br><br>
        <div class="friends">
          <p>Друзья <a style="margin-left: 10px;" href=""> Найти ешё друзей</a></p>
          <hr>
          
          <div class="firendsOnlineList">
            <p><a href="">Кевин Митник </a> Бил в сети 20 мин. назад<p>
          </div>
          <hr>
           <div class="firendsOnlineList">
            <p><a href="">Павел Дуров </a> Бил в сети час назад<p>
          </div>
          <hr>

        </div>
          <div class="chat"></div>

        </div>
      </div>

        <div class="col-lg-3 col-md-3 col-xs-12">
          <p class="">BANNER</p>
          <br>
 
        </div>
          
        

      </div>
    </div>

   

    <div style="margin-top: 1000px;"></div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

socset/templates/accounts/listusers.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="img/icon.png" type="image/png">
    <link rel="shortcut icon" href="{% static 'img/icon.png' %}" type="image/png">
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  
    <title>FaceVkInsta</title>
  </head>
  <body>
    
    
{% include 'navbar.html' %}


<br><br><br><br>
    <div class="container">  
      <div class="row"> 
        
        <div class="col-lg-3 col-md-3 col-xs-12 rightcoolsite">
          <p class="friendsonline">Друзья онлайн</p>
          <br>
          <hr>

          <div class="firendsOnlineList">
            <p><a href="">Павел Дуров </a> Бил в сети час назад<p>
          </div>
          <hr>
          <div class="firendsOnlineList">
            <p><a href="">Кевин Митник </a> Бил в сети 20 мин. назад<p>
          </div>
          <hr>

        </div>
          
        <div class="col-lg-9 col-md-9 col-xs-12 leftsitenews">
          {% for users in users_list %}
          <div class="listuserdiv">
           <p><img class="img-fluid imglistusers" src="{{ users.user.userprofile.avatar.url }}" alt="">{{ users.user.get_full_name }}</p>
            <a href="{{ users.user_get_absolute_url }}">
            Перейти профиль</a>
          </div>
          <br>
          <hr>
          {% endfor %}
        </div>

      </div>
    </div>

   

    <div style="margin-top: 1000px;"></div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

socset/templates/accounts/login.html
{% extends 'landing.html' %}
{% block content %}
<form method="POST" action="">
 {% csrf_token %}
              <input type="text" name="username" class="form-control" placeholder="Логин" required id="id_username">
              <br>
              <input type="password" name="password"
			  required id="id_password"
              class="form-control" placeholder="Пароль">
              <br>
              <p class="forgotpassword"><a href="/register/">
              Нет аккаунта?</a></p>
              
              <button class="loginbutton btn" 
         name="submit" 
         type="submit">
         Войти</button>
            </form>

          <!-- <form class="formclasslogin" action=""> 
<tr><th></th><td><input type="text" name="username" required id="id_username" /></td></tr>

<tr><th></th><td><input type="password" name="password" 
 required id="id_password" /></td></tr>
</form> -->





{% endblock content %}

socset/templates/accounts/profilemy.html
{% load static %}
{% load crispy_forms_tags %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="img/icon.png" type="image/png">
    <link rel="shortcut icon" href="{% static 'img/icon.png' %}" type="image/png">
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  
    <title>FaceVkInsta</title>
  </head>
  <body>
    
    

{% include 'navbar.html' %}

<br><br><br><br>
    <div class="container">  
      <div class="row"> 
          
          
        <div class="col-lg-9 col-md-9 col-xs-12 leftprofile">
          <div class="leftprofilecolor">
          <div class="row">

          <div class="imgandop col-lg-4">

          {% if user.userprofile.avatar %}

          <img class="img-fluid img-thumbnail img-profile" 
          src="{{ user.userprofile.avatar.url }}" alt="">
          {% else %}
          <img class="img-fluid" 
          src="{% static 'img/default_avatar.png' %}">
          <br>
          <form method="post" action="." enctype='multipart/form-data'>
          {% csrf_token %}
          {{ forming|crispy }}
      <input type="submit" value="Загружать фото"
      class="btn btn-default">
      </form>
      {% endif %}

          
          </div>
          <div class="nameprofile col-lg-8">
            <p class="namepr">{{ user.get_full_name }}</p>
            <a href="/update/">Изменить данные</a>
            <p>Город - 
<a href="/listusers/?q={{ user.userprofile.city }}">
            {{ user.userprofile.city }}</a></p>
            <p>Место работы - 
<a href="/listusers/?q={{ user.userprofile.placework }}">
            {{ user.userprofile.placework }}</a></p>
          </div>
          
        </div>
        
        <br><br>
        <div class="friends">
          <p>Друзья <a style="margin-left: 10px;" href="/listusers/"> Найти ешё друзей</a></p>
          <hr>
          
      {% for users in zayavka_list %}
{% if users.user in request.user.userprofile.friends.all %}
          <div class="firendsOnlineList">
            <p>
            <a href="{{ users.user_get_absolute_url }}">
          {{ users.user.get_full_name }}</a>
          </p> 
            Бил в сети {{ users.last_activity|timesince}} назад<p>
          </div>
          <hr>
          {% endif %}
          {% endfor %}


        </div>
          <div class="chat"></div>

        </div>
      </div>

        <div class="col-lg-3 col-md-3 col-xs-12">
          <p class="">BANNER</p>
          <br>
 
        </div>
          
        

      </div>
    </div>

   

    <div style="margin-top: 1000px;"></div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

socset/templates/accounts/register.html
{% extends 'landing.html' %}
{% block content %}
<!-- <form class="formclasslogin" action="" method="POST" 
 enctype="multipart/form-data">
 {% csrf_token %}
            <tr><th></th><td> <input type="text" name="username" class="form-control" placeholder="Логин" required id="id_username">
            </td></tr>
              <br>
              <tr><th></th><td>
              <input type="password" name="password"
			  required id="id_password"
              class="form-control" placeholder="Пароль"></td></tr>
              <br>
              <p class="forgotpassword"><a href="#">
              Забыли пароль?</a></p>
              
              <button class="loginbutton btn" name="submit" type="submit">Войти</button>
            </form> -->
<form method="POST" action="">
{% csrf_token %}
         
         <input type="text" name="first_name" 
         class="form-control" 
  placeholder="Имя" 
 required id="id_first_name">
 <br>
<input type="text" name="last_name" 
 class="form-control" 
  placeholder="Фамилия"
 required id="id_last_name">
 <br>
<input type="text" name="email"
 class="form-control" 
 placeholder="Email" 
 required id="id_email">
<br>
<input type="text" name="username" class="form-control" 
 placeholder="Логин" 
 required id="id_username">
 <br>
  <input type="password" name="password"
      required id="id_password"
      class="form-control" placeholder="Пароль">
      <br>
      <p class="forgotpassword"><a href="/">
              Есть аккаунт?</a></p>
        

         <button class="loginbutton btn" 
         name="submit" 
         type="submit">
         Регистрация</button>
</form>




{% endblock content %}